spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your-db-name
    username: your-username
    password: your-password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    com.boilerplate: DEBUG
    org.springframework.security: DEBUG
